### PR TITLE
Added sample for jni kotlin

### PR DESCRIPTION
**Pull request by pramonow**
sample for using jni in kotlin, please review thanks

### CODE REVIEW

**Comment by amanjeetsingh150** [comment]
Hey @pramonow Can you add GIF or screenshots for the project and make a readme for this project.
Thanks for the contribution 👍

**Comment by pramonow** [comment]
right, will add the readme on it later

**Comment by pramonow** [comment]
Added readme for it, please look through it, thanks!

**Review by amanjeetsingh150 — APPROVED** [review]

**Comment by amanjeetsingh150** [comment]
Thanks @pramonow merged !! 👍

**Comment by pramonow** [comment]
nice! thanks @amanjeetsingh150

**Pull request merged**
