### PR TITLE
Added widget example

### PR DESCRIPTION
**Pull request by pramonow**
Hi, added example for android widget with kotlin

### CODE REVIEW

**Comment by amanjeetsingh150** [comment]
Hey @pramonow can you paste or integrate a screenshot here or in the project itself? It will be easy to get it.

Thanks,
Amanjeet Singh

**Comment by pramonow** [comment]
Hi, of course
Will push the screenshoot of the sample soon

**Comment by pramonow** [comment]
Hi i have added preview gif image for rough explanation on what this app is doing, thanks

**Comment by pramonow** [comment]
Hi @amanjeetsingh150, i have added preview gif image for rough explanation on what this app is doing, thanks

**Comment by amanjeetsingh150** [comment]
Hey thanks @pramonow 👍 merged !!

**Comment by pramonow** [comment]
thanks! really appreciate it

**Pull request merged**
